services:
  console.create_users:
    class: WP\Console\Command\Create\UsersCommand
    arguments: ['@console.create_user_data', '@console.site', '@console.wordpress_api']
    tags:
      - { name: wordpress.command }
  console.create_roles:
    class: WP\Console\Command\Create\RolesCommand
    arguments: ['@console.create_role_data']
    tags:
      - { name: wordpress.command }