services:
  console.generate_command:
    class: WP\Console\Command\Generate\CommandCommand
    arguments: ['@console.command_generator', '@console.extension_manager', '@console.validator', '@console.string_converter' ]
    tags:
      - { name: wordpress.command }
  console.generate_plugin:
    class: WP\Console\Command\Generate\PluginCommand
    arguments: ['@console.plugin_generator', '@console.validator', '@app.root', '@console.string_converter', '@http_client', '@console.site']
    tags:
      - { name: wordpress.command }
  console.generate_meta_box:
    class: WP\Console\Command\Generate\MetaBoxCommand
    arguments: ['@console.meta_box_generator', '@console.extension_manager', '@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_taxonomy:
    class: WP\Console\Command\Generate\TaxonomyCommand
    arguments: ['@console.taxonomy_generator', '@console.extension_manager', '@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_theme:
    class: WP\Console\Command\Generate\ThemeCommand
    arguments: ['@console.theme_generator', '@console.validator', '@app.root', '@console.string_converter', '@http_client', '@console.site']
    tags:
      - { name: wordpress.command }
  console.generate_shortcode:
    class: WP\Console\Command\Generate\ShortcodeCommand
    arguments: ['@console.shortcode_generator', '@console.extension_manager', '@console.site','@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_post_type:
    class: WP\Console\Command\Generate\PostTypeCommand
    arguments: ['@console.post_type_generator', '@console.extension_manager', '@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_menu:
    class: WP\Console\Command\Generate\MenuCommand
    arguments: ['@console.menu_generator', '@console.extension_manager', '@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_toolbar:
    class: WP\Console\Command\Generate\ToolbarCommand
    arguments: ['@console.toolbar_generator', '@console.extension_manager', '@console.validator', '@console.string_converter', '@console.site']
    tags:
      - { name: wordpress.command }
  console.generate_sidebar:
    class: WP\Console\Command\Generate\SidebarCommand
    arguments: ['@console.sidebar_generator', '@console.extension_manager', '@console.validator', '@console.string_converter', '@console.site']
    tags:
      - { name: wordpress.command }
  console.generate_quicktag:
    class: WP\Console\Command\Generate\QuickTagCommand
    arguments: ['@console.quicktag_generator', '@console.extension_manager', '@console.validator', '@console.string_converter', '@console.site']
    tags:
      - { name: wordpress.command }
  console.generate_widget:
    class: WP\Console\Command\Generate\WidgetCommand
    arguments: ['@console.widget_generator', '@console.extension_manager', '@console.validator', '@console.string_converter']
    tags:
      - { name: wordpress.command }
  console.generate_register_style:
    class: WP\Console\Command\Generate\RegisterStyleCommand
    arguments: ['@console.register_style_generator', '@console.extension_manager', '@console.validator', '@console.string_converter', '@console.site']
    tags:
      - { name: wordpress.command }